### ISSUE TITLE
Requirement of Requests package problematic

### ISSUE THREAD

**Issue by BrianHenryIE** [Art4/WP-Requests-PSR18-Adapter#16]
I've been getting errors using [PhpStan WordPress](https://github.com/szepeviktor/phpstan-wordpress):

```bash
$ phpstan analyse 
Note: Using configuration file /Users/brianhenry/Sites/bh-wp-bitcoin-gateway/phpstan.neon.
Fatal error: Cannot declare class WpOrg\Requests\Autoload, because the name is already in use in /Users/brianhenry/Sites/bh-wp-bitcoin-gateway/vendor/php-stubs/wordpress-stubs/wordpress-stubs.php on line 18703
Script phpstan analyse --memory-limit 1G handling the cs event returned with error code 255
```

I think there are two ways to address it. 

Add documentation to the README: 
```bash
# Add a `provide` entry to tell Composer not to install Requests.
# brew install jq sponge
cat composer.json | jq ".provide += { \"rmccue/requests\": \"*\" }" | sponge composer.json
```
https://github.com/Art4/WP-Requests-PSR18-Adapter/compare/main...BrianHenryIE:WP-Requests-PSR18-Adapter:patch-1

Or move `"rmccue/requests": "^1.8 || ^2.0"` from `require` to `require-dev` and add `suggest`: 
```json
"suggest": {
    "rmccue/requests": "Requests is included with WordPress but must be required independently otherwise."
}
```
https://github.com/Art4/WP-Requests-PSR18-Adapter/compare/main...BrianHenryIE:WP-Requests-PSR18-Adapter:patch-2

I think the latter should work. It's more drastic than the first but more straightforward for consumers of this package.

**Comment by Art4** [comment]
If one is using the library in a WordPress context but uses composer for installation, I recommend to use [`replace`](https://getcomposer.org/doc/04-schema.md#replace) in composer to not install `rmccue/requests` to times. The `composer.json` could look like this:

```json
{
    "name": "art4/testproject",
    "type": "project",
    "require": {
        "art4/requests-psr18-adapter": "^1.1"
    },
    "require-dev": {
        "phpstan/phpstan": "^1.10",
        "szepeviktor/phpstan-wordpress": "^1.3",
        "phpunit/phpunit": "^10.4"
    },
    "replace": {
        "rmccue/requests": "*"
    }
}
```
