### ISSUE TITLE
Fatal error due to missing return types

### ISSUE THREAD

**Issue by BrianHenryIE** [Art4/WP-Requests-PSR18-Adapter#8]
When I try to run the repo's PHPUnit tests, unchanged, I get:

```
Fatal error: Declaration of Art4\Requests\Psr\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string in /Users/brianhenry/Sites/WP-Requests-PSR18-Adapter/src/Psr/Request.php on line 115
```

The problem is that `psr/http-message` [introduced return types in v2.0](https://github.com/php-fig/http-message/compare/1.1...2.0). And `psr/http-client` allowed `"psr/http-message": "^1.0 || ^2.0"` in [v1.0.2](https://github.com/php-fig/http-client/compare/1.0.1...1.0.2)

Adding a requirement on `"psr/http-message": "^1.0"` works to fix the issue.

**Comment by Art4** [comment]
Thank you. I just released 1.0.1
